# Generated by Django 3.0.3 on 2020-10-14 16:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201008_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pizza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('בטטה', 'בטטה'), ('חצילים', 'חצילים'), ('בולגרית', 'בולגרית'), ('בצל סגול', 'בצל סגול '), ('פטריות', 'פטריות'), ('זיתים', 'זיתים'), ('תירס', 'תירס'), ('עגבניה', 'עגבניה'), ('פלפל חריף', 'פלפל חריף')], max_length=63),
        ),
    ]
