# Generated by Django 3.0.3 on 2020-10-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201014_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toppings',
        ),
    ]
